services:
  harbor-web:
    image: harbor-web:latest
    container_name: harbor-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1420:1420"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TAURI_DEV_HOST=0.0.0.0
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
